-- Ai Recipy demo seed: placeholder creators and listings (credited, not AI-made).
-- Generated from lib/mock. Safe to re-run: skips rows that already exist.

insert into public.profiles (username, display_name, bio, avatar_url, is_seller) values ('mira.frames', 'Mira Okafor', 'Cinematic product shots and moody light. Ex-commercial DP.', 'https://api.dicebear.com/9.x/notionists/svg?seed=mira&backgroundColor=ff5e5b,3d5afe,ffd23f,2ec4b6,c77dff,ff9f1c', true) on conflict (username) do nothing;
insert into public.profiles (username, display_name, bio, avatar_url, is_seller) values ('kenji_lab', 'Kenji Ito', 'Stylised motion, loops and anime-adjacent worlds.', 'https://api.dicebear.com/9.x/notionists/svg?seed=kenji&backgroundColor=ff5e5b,3d5afe,ffd23f,2ec4b6,c77dff,ff9f1c', true) on conflict (username) do nothing;
insert into public.profiles (username, display_name, bio, avatar_url, is_seller) values ('solenne', 'Solenne Marchetti', 'Editorial portraits and fashion stills.', 'https://api.dicebear.com/9.x/notionists/svg?seed=solenne&backgroundColor=ff5e5b,3d5afe,ffd23f,2ec4b6,c77dff,ff9f1c', true) on conflict (username) do nothing;
insert into public.profiles (username, display_name, bio, avatar_url, is_seller) values ('toonsmith', 'Ava Lindqvist', 'Cartoon worlds, squash-and-stretch characters and chaotic pets.', 'https://api.dicebear.com/9.x/notionists/svg?seed=ava&backgroundColor=ff5e5b,3d5afe,ffd23f,2ec4b6,c77dff,ff9f1c', true) on conflict (username) do nothing;
insert into public.profiles (username, display_name, bio, avatar_url, is_seller) values ('pixelmonk', 'Ravi Desai', 'Anime-style action and hand-drawn looks from video models.', 'https://api.dicebear.com/9.x/notionists/svg?seed=ravi&backgroundColor=ff5e5b,3d5afe,ffd23f,2ec4b6,c77dff,ff9f1c', true) on conflict (username) do nothing;
insert into public.profiles (username, display_name, bio, avatar_url, is_seller) values ('dax.builds', 'Dax Romero', 'Architecture, interiors, and impossible spaces.', 'https://api.dicebear.com/9.x/notionists/svg?seed=dax&backgroundColor=ff5e5b,3d5afe,ffd23f,2ec4b6,c77dff,ff9f1c', true) on conflict (username) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'junkyard-rocket-pets', p.id, 'Junkyard rocket pets', 'A cat and a dog strap into a scrap-metal rocket. Rubbery squash-and-stretch, consistent characters across every cut.', 'video', '/clips/wingit-rocket.mp4', '/posters/wingit-rocket.jpg', null, null, $json${"work":"WING IT! (1:36–1:48)","author":"Blender Foundation / Blender Studio","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","sourceUrl":"https://commons.wikimedia.org/wiki/File:WING_IT!_-_Blender_Open_Movie-full_movie.webm"}$json$::jsonb, 'kling', '2.5', array['cartoon','pets','comedy','3d']::text[], 1400, $json${"mode":"single"}$json$::jsonb, false, 31200, 410, 2900, 9860, 99, $json${"counts":{"prompts":3,"settings":5,"assets":2,"editStack":2,"failures":2},"teaser":{"label":"Character sheet","text":"Stylised 3D cartoon, a scrappy orange tabby cat and a goofy brown dog, b"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-rocket-1/480/480","note":"Dog turned into a cat halfway: no character sheet attached."},{"imageUrl":"https://picsum.photos/seed/fail-rocket-2/480/480","note":null}],"settingKeys":["Mode","Aspect","Duration","Character ref","Seed"],"assetNames":["Cat & dog turnaround sheet","Junkyard rocket concept"],"editTools":["CapCut","Topaz Video AI"]}$json$::jsonb, '2026-10-04T09:00:00Z'
from public.profiles p where p.username = 'toonsmith'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Character sheet","text":"Stylised 3D cartoon, a scrappy orange tabby cat and a goofy brown dog, big expressive eyes, chunky silhouettes, Pixar-like subsurface skin, turnaround sheet, neutral background"},{"label":"Shot · lift-off","text":"The cat and dog clutch the controls of a rickety rocket built from junkyard scraps, bolts popping off, exaggerated squash and stretch, camera shakes on ignition, warm farmyard sunset"},{"label":"Negative","text":"realistic fur, extra limbs, text, logo, warped faces"}]$json$::jsonb, $json$[{"key":"Mode","value":"Professional"},{"key":"Aspect","value":"9:16"},{"key":"Duration","value":"10s"},{"key":"Character ref","value":"Sheet A, weight 0.8"},{"key":"Seed","value":"77120"}]$json$::jsonb, $json$[{"name":"Cat & dog turnaround sheet","note":"Generated first, then used as reference"},{"name":"Junkyard rocket concept","note":"Midjourney v7, 4 variations"}]$json$::jsonb, $json$[{"tool":"CapCut","note":"Speed ramp at ignition, 1.4×"},{"tool":"Topaz Video AI","note":"Upscale + frame interpolation to 48fps"}]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-rocket-1/480/480","note":"Dog turned into a cat halfway: no character sheet attached."},{"imageUrl":"https://picsum.photos/seed/fail-rocket-2/480/480","note":"Rocket melted on lift-off. 'Rigid metal parts' fixed it."}]$json$::jsonb from public.listings where slug = 'junkyard-rocket-pets'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'anime-lightning-duel', p.id, 'Anime lightning duel', 'Hand-drawn anime look with crackling lightning and smear frames. Reads like 2D cel animation, not 3D.', 'video', '/clips/hero-lightning.mp4', '/posters/hero-lightning.jpg', null, null, $json${"work":"HERO (1:37–1:49)","author":"Blender Foundation / Blender Studio","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","sourceUrl":"https://commons.wikimedia.org/wiki/File:HERO_-_Blender_Open_Movie-full_movie.webm"}$json$::jsonb, 'runway', 'Gen-4', array['anime','2d','action','lightning']::text[], 1800, $json${"mode":"single"}$json$::jsonb, false, 28700, 330, 2410, 8194, 97, $json${"counts":{"prompts":2,"settings":3,"assets":1,"editStack":2,"failures":1},"teaser":{"label":"Main","text":"2D hand-drawn anime action, a young hero raises a sword as forked lightn"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-anime-1/480/480","note":"Came out glossy 3D until '3D render' went in the negative."}],"settingKeys":["Style ref","Motion","Duration"],"assetNames":["Ink keyframes (6)"],"editTools":["After Effects","After Effects"]}$json$::jsonb, '2026-10-03T15:00:00Z'
from public.profiles p where p.username = 'pixelmonk'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"2D hand-drawn anime action, a young hero raises a sword as forked lightning crackles across a stormy sky, thick ink outlines, cel shading, smear frames on fast motion, 12fps on twos"},{"label":"Negative","text":"3D render, glossy, photoreal, motion blur"}]$json$::jsonb, $json$[{"key":"Style ref","value":"Hand-drawn keyframe set"},{"key":"Motion","value":"7"},{"key":"Duration","value":"10s"}]$json$::jsonb, $json$[{"name":"Ink keyframes (6)","note":"Drawn roughs used as image prompts"}]$json$::jsonb, $json$[{"tool":"After Effects","note":"Hold every other frame for on-twos timing"},{"tool":"After Effects","note":"Flash frames on each lightning strike"}]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-anime-1/480/480","note":"Came out glossy 3D until '3D render' went in the negative."}]$json$::jsonb from public.listings where slug = 'anime-lightning-duel'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'mushroom-sprite-ambush', p.id, 'Mushroom sprite ambush', 'Tiny forest sprites spring out of the moss. Saturated, storybook-gone-wrong energy.', 'video', '/clips/sprite-ambush.mp4', '/posters/sprite-ambush.jpg', null, null, $json${"work":"Sprite Fright (0:35–0:47)","author":"Blender Foundation / Blender Studio","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","sourceUrl":"https://commons.wikimedia.org/wiki/File:Sprite_Fright_-_Blender_Open_Movie-full_movie.webm"}$json$::jsonb, 'veo', '3.1', array['cartoon','creatures','forest','spooky']::text[], 1600, $json${"mode":"single"}$json$::jsonb, false, 25100, 290, 2200, 7480, 96, $json${"counts":{"prompts":1,"settings":3,"assets":0,"editStack":1,"failures":1},"teaser":{"label":"Main","text":"Stylised 3D animation, a mossy forest floor at dusk, tiny mushroom-cappe"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-sprite-1/480/480","note":"Sprites looked like real mushrooms without 'glowing eyes'."}],"settingKeys":["Aspect","Seed","Guidance"],"assetNames":[],"editTools":["DaVinci Resolve"]}$json$::jsonb, '2026-10-02T12:00:00Z'
from public.profiles p where p.username = 'toonsmith'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Stylised 3D animation, a mossy forest floor at dusk, tiny mushroom-capped sprites with glowing eyes pop out of the moss all at once, playful-creepy, saturated greens and magentas, low dolly in"}]$json$::jsonb, $json$[{"key":"Aspect","value":"9:16"},{"key":"Seed","value":"31337"},{"key":"Guidance","value":"8"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"tool":"DaVinci Resolve","note":"Teal-magenta grade, +12 saturation"}]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-sprite-1/480/480","note":"Sprites looked like real mushrooms without 'glowing eyes'."}]$json$::jsonb from public.listings where slug = 'mushroom-sprite-ambush'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'llama-vs-penguin', p.id, 'Llama vs penguin standoff', 'A smug llama and a tiny penguin square off in the snow. Free recipe, great starter.', 'video', '/clips/llama-penguin.mp4', '/posters/llama-penguin.jpg', null, null, $json${"work":"Caminandes 3: Llamigos (1:18–1:30)","author":"Blender Foundation / Blender Studio","license":"CC BY 3.0","licenseUrl":"https://creativecommons.org/licenses/by/3.0/","sourceUrl":"https://commons.wikimedia.org/wiki/File:Caminandes_3_-_Llamigos_-_Blender_Animated_Short.webm"}$json$::jsonb, 'veo', '3.1', array['cartoon','animals','snow','free']::text[], 0, $json${"mode":"single"}$json$::jsonb, false, 40300, 2100, 3300, 11220, 94, $json${"counts":{"prompts":1,"settings":2,"assets":0,"editStack":0,"failures":1},"teaser":{"label":"Main","text":"Cartoon 3D short, a fluffy llama with a smug expression stares down a ti"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-llama-1/480/480","note":"Penguin grew to llama size. Say 'tiny' twice."}],"settingKeys":["Aspect","Duration"],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-10-01T10:00:00Z'
from public.profiles p where p.username = 'toonsmith'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Cartoon 3D short, a fluffy llama with a smug expression stares down a tiny penguin on a snowy Patagonian plain, comedic timing, wide lens, bright overcast light"}]$json$::jsonb, $json$[{"key":"Aspect","value":"16:9"},{"key":"Duration","value":"8s"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-llama-1/480/480","note":"Penguin grew to llama size. Say 'tiny' twice."}]$json$::jsonb from public.listings where slug = 'llama-vs-penguin'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'caffeine-rush-trip', p.id, 'Caffeine rush trip', 'One sip and the world melts into neon swirls. A psychedelic transition you can reuse.', 'video', '/clips/coffee-rush.mp4', '/posters/coffee-rush.jpg', null, null, $json${"work":"Coffee Run (2:00–2:12)","author":"Blender Foundation / Blender Studio","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","sourceUrl":"https://commons.wikimedia.org/wiki/File:Coffee_Run_-_Blender_Open_Movie-full_movie.webm"}$json$::jsonb, 'sora', '2', array['psychedelic','transition','cartoon']::text[], 1500, $json${"mode":"single"}$json$::jsonb, false, 19800, 240, 1700, 5780, 93, $json${"counts":{"prompts":1,"settings":2,"assets":0,"editStack":1,"failures":1},"teaser":{"label":"Main","text":"Stylised animation, a sleepy young woman gulps espresso and the café mel"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-coffee-1/480/480","note":"Swirl started too early: split into two prompts."}],"settingKeys":["Duration","Seed"],"assetNames":[],"editTools":["After Effects"]}$json$::jsonb, '2026-10-03T08:00:00Z'
from public.profiles p where p.username = 'kenji_lab'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Stylised animation, a sleepy young woman gulps espresso and the café melts into swirling neon paint, colours bleed and spiral, camera pushes in fast, playful psychedelic transition"}]$json$::jsonb, $json$[{"key":"Duration","value":"12s"},{"key":"Seed","value":"99001"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"tool":"After Effects","note":"Radial blur + chromatic aberration on the swirl"}]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-coffee-1/480/480","note":"Swirl started too early: split into two prompts."}]$json$::jsonb from public.listings where slug = 'caffeine-rush-trip'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'forest-spirit-awakening', p.id, 'Forest spirit awakening', 'A painterly fantasy moment: a girl meets a giant forest spirit. Big, soft, cinematic.', 'video', '/clips/spring-spirit.mp4', '/posters/spring-spirit.jpg', null, null, $json${"work":"Spring (5:12–5:24)","author":"Blender Foundation / Blender Studio","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","sourceUrl":"https://commons.wikimedia.org/wiki/File:Spring_-_Blender_Open_Movie.webm"}$json$::jsonb, 'veo', '3.1', array['fantasy','painterly','cinematic']::text[], 2000, $json${"mode":"single"}$json$::jsonb, false, 16400, 180, 1500, 5100, 92, $json${"counts":{"prompts":1,"settings":2,"assets":1,"editStack":1,"failures":1},"teaser":{"label":"Main","text":"Painterly 3D fantasy, a shepherd girl in a misty mountain forest looks u"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-spirit-1/480/480","note":"Spirit kept appearing as a bear. 'Ancient, mossy, antlers' fixed it."}],"settingKeys":["Aspect","Seed"],"assetNames":["Spirit silhouette sketch"],"editTools":["DaVinci Resolve"]}$json$::jsonb, '2026-09-30T18:00:00Z'
from public.profiles p where p.username = 'kenji_lab'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Painterly 3D fantasy, a shepherd girl in a misty mountain forest looks up as an enormous ancient forest spirit opens its glowing eyes, god rays, soft volumetric fog, slow crane up"}]$json$::jsonb, $json$[{"key":"Aspect","value":"21:9 → crop 9:16"},{"key":"Seed","value":"40404"}]$json$::jsonb, $json$[{"name":"Spirit silhouette sketch"}]$json$::jsonb, $json$[{"tool":"DaVinci Resolve","note":"Film grain + halation"}]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-spirit-1/480/480","note":"Spirit kept appearing as a bear. 'Ancient, mossy, antlers' fixed it."}]$json$::jsonb from public.listings where slug = 'forest-spirit-awakening'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'pop-art-heart-burst', p.id, 'Pop-art heart burst', 'Flat 2D pop-art with bouncing hearts and bold colour blocks. Perfect for loops and stickers.', 'video', '/clips/glass-heart.mp4', '/posters/glass-heart.jpg', null, null, $json${"work":"Glass Half (0:30–0:42)","author":"Blender Foundation / Blender Studio","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","sourceUrl":"https://commons.wikimedia.org/wiki/File:Glass_Half_-_Blender_Open_Movie-full_movie.webm"}$json$::jsonb, 'midjourney', 'v7 video', array['2d','pop art','loop','colorful']::text[], 700, $json${"mode":"single"}$json$::jsonb, false, 12300, 150, 1100, 3740, 90, $json${"counts":{"prompts":1,"settings":2,"assets":0,"editStack":0,"failures":1},"teaser":{"label":"Main","text":"Flat 2D cartoon, pop-art colour blocks, a character with a huge grin as "},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-pop-1/480/480","note":"Too many hearts: became wallpaper. Cap it at 'five hearts'."}],"settingKeys":["Motion","Stylize"],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-09-29T11:00:00Z'
from public.profiles p where p.username = 'pixelmonk'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Flat 2D cartoon, pop-art colour blocks, a character with a huge grin as red hearts burst and bounce around them, bold outlines, limited palette, looping"}]$json$::jsonb, $json$[{"key":"Motion","value":"high"},{"key":"Stylize","value":"400"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-pop-1/480/480","note":"Too many hearts: became wallpaper. Cap it at 'five hearts'."}]$json$::jsonb from public.listings where slug = 'pop-art-heart-burst'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'cosmic-vortex-dive', p.id, 'Cosmic vortex dive', 'Fall through a kaleidoscope of colour. An endlessly loopable sci-fi tunnel.', 'video', '/clips/cosmos-vortex.mp4', '/posters/cosmos-vortex.jpg', null, null, $json${"work":"Cosmos Laundromat (8:16–8:28)","author":"Blender Foundation / Blender Studio","license":"CC BY-SA 3.0","licenseUrl":"https://creativecommons.org/licenses/by-sa/3.0/","sourceUrl":"https://commons.wikimedia.org/wiki/File:Cosmos_Laundromat_-_First_Cycle_-_Official_Blender_Foundation_release.webm"}$json$::jsonb, 'runway', 'Gen-4', array['sci-fi','psychedelic','loop']::text[], 1200, $json${"mode":"single"}$json$::jsonb, false, 14900, 160, 1250, 4250, 89, $json${"counts":{"prompts":1,"settings":2,"assets":0,"editStack":0,"failures":1},"teaser":{"label":"Main","text":"Surreal sci-fi animation, the camera dives into a swirling cosmic vortex"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-vortex-1/480/480","note":"Loop seam jumped. Match first and last frame prompts."}],"settingKeys":["Loop","Seed"],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-09-28T20:00:00Z'
from public.profiles p where p.username = 'dax.builds'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Surreal sci-fi animation, the camera dives into a swirling cosmic vortex of liquid colour, fractal petals unfolding, hyper-saturated magenta and gold, seamless loop"}]$json$::jsonb, $json$[{"key":"Loop","value":"On"},{"key":"Seed","value":"60606"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-vortex-1/480/480","note":"Loop seam jumped. Match first and last frame prompts."}]$json$::jsonb from public.listings where slug = 'cosmic-vortex-dive'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'hand-drawn-hero-walk', p.id, 'Hand-drawn hero walk', 'A confident 2D walk cycle with real hand-drawn wobble. Swap in your own character.', 'video', '/clips/hero-walk.mp4', '/posters/hero-walk.jpg', null, null, $json${"work":"HERO (0:38–0:50)","author":"Blender Foundation / Blender Studio","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","sourceUrl":"https://commons.wikimedia.org/wiki/File:HERO_-_Blender_Open_Movie-full_movie.webm"}$json$::jsonb, 'kling', '2.5', array['2d','anime','walk cycle']::text[], 1100, $json${"mode":"single"}$json$::jsonb, false, 9800, 120, 860, 2924, 85, $json${"counts":{"prompts":1,"settings":1,"assets":0,"editStack":0,"failures":1},"teaser":{"label":"Main","text":"2D hand-drawn animation, a young swordsman strides toward camera with a "},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-walk-1/480/480","note":"Legs swapped mid-stride. Generate 5s chunks."}],"settingKeys":["Duration"],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-09-27T09:00:00Z'
from public.profiles p where p.username = 'pixelmonk'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"2D hand-drawn animation, a young swordsman strides toward camera with a cocky smile, line boil on the outlines, flat cel colours, dusty village street"}]$json$::jsonb, $json$[{"key":"Duration","value":"5s ×2"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-walk-1/480/480","note":"Legs swapped mid-stride. Generate 5s chunks."}]$json$::jsonb from public.listings where slug = 'hand-drawn-hero-walk'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'barnyard-launch-gone-wrong', p.id, 'Barnyard launch gone wrong', 'The rocket sputters, the chickens scatter, chaos ensues. Comedy timing is in the recipe.', 'video', '/clips/wingit-launch.mp4', '/posters/wingit-launch.jpg', null, null, $json${"work":"WING IT! (2:06–2:18)","author":"Blender Foundation / Blender Studio","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","sourceUrl":"https://commons.wikimedia.org/wiki/File:WING_IT!_-_Blender_Open_Movie-full_movie.webm"}$json$::jsonb, 'sora', '2', array['cartoon','comedy','chaos']::text[], 900, $json${"mode":"single"}$json$::jsonb, false, 11200, 130, 940, 3196, 83, $json${"counts":{"prompts":1,"settings":1,"assets":0,"editStack":0,"failures":1},"teaser":{"label":"Main","text":"Cartoon 3D comedy, a homemade rocket sputters smoke in a barnyard, chick"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-barn-1/480/480","note":"Chickens multiplied to 40. 'Three chickens' fixed it."}],"settingKeys":["Duration"],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-09-26T14:00:00Z'
from public.profiles p where p.username = 'toonsmith'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Cartoon 3D comedy, a homemade rocket sputters smoke in a barnyard, chickens scatter, a cat clings to the hull, exaggerated reactions, bright midday light"}]$json$::jsonb, $json$[{"key":"Duration","value":"12s"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-barn-1/480/480","note":"Chickens multiplied to 40. 'Three chickens' fixed it."}]$json$::jsonb from public.listings where slug = 'barnyard-launch-gone-wrong'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'campfire-squad', p.id, 'Campfire squad close-ups', 'Expressive cartoon faces around a campfire. A masterclass in consistent characters.', 'video', '/clips/sprite-campfire.mp4', '/posters/sprite-campfire.jpg', null, null, $json${"work":"Sprite Fright (3:10–3:22)","author":"Blender Foundation / Blender Studio","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","sourceUrl":"https://commons.wikimedia.org/wiki/File:Sprite_Fright_-_Blender_Open_Movie-full_movie.webm"}$json$::jsonb, 'kling', '2.5', array['cartoon','characters','night']::text[], 1000, $json${"mode":"single"}$json$::jsonb, false, 8700, 95, 700, 2380, 82, $json${"counts":{"prompts":1,"settings":1,"assets":0,"editStack":0,"failures":1},"teaser":{"label":"Main","text":"Stylised 3D cartoon, five friends around a campfire in a dark forest, wa"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-camp-1/480/480","note":"Faces swapped between friends. One ref sheet per character."}],"settingKeys":["Character refs"],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-09-25T19:00:00Z'
from public.profiles p where p.username = 'toonsmith'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Stylised 3D cartoon, five friends around a campfire in a dark forest, warm firelight on expressive faces, slow push-in, cosy-creepy mood"}]$json$::jsonb, $json$[{"key":"Character refs","value":"5 sheets, weight 0.7"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-camp-1/480/480","note":"Faces swapped between friends. One ref sheet per character."}]$json$::jsonb from public.listings where slug = 'campfire-squad'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'last-stand-vs-robot', p.id, 'Last stand vs the robot', 'A gritty sci-fi standoff with a towering machine. Moody, cinematic and tense.', 'video', '/clips/charge-robot.mp4', '/posters/charge-robot.jpg', null, null, $json${"work":"Charge (1:15–1:27)","author":"Blender Foundation / Blender Studio","license":"CC BY 4.0","licenseUrl":"https://creativecommons.org/licenses/by/4.0/","sourceUrl":"https://commons.wikimedia.org/wiki/File:Charge_-_Blender_Open_Movie-full_movie.webm"}$json$::jsonb, 'sora', '2', array['sci-fi','robot','cinematic']::text[], 1300, $json${"mode":"single"}$json$::jsonb, false, 10100, 110, 820, 2788, 81, $json${"counts":{"prompts":1,"settings":1,"assets":0,"editStack":0,"failures":1},"teaser":{"label":"Main","text":"Cinematic 3D animation, an old man in a wrecked industrial yard faces a "},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-robot-1/480/480","note":"Robot looked cute. 'Industrial, menacing, scratched paint'."}],"settingKeys":["Aspect"],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-09-24T21:00:00Z'
from public.profiles p where p.username = 'dax.builds'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Cinematic 3D animation, an old man in a wrecked industrial yard faces a towering security robot, red warning lights, rain, low angle, tense standoff"}]$json$::jsonb, $json$[{"key":"Aspect","value":"2.39:1"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-robot-1/480/480","note":"Robot looked cute. 'Industrial, menacing, scratched paint'."}]$json$::jsonb from public.listings where slug = 'last-stand-vs-robot'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'enchanted-steam-creek', p.id, 'Enchanted steam creek', 'A glowing river winds through a fantasy forest at night. Calm, magical and loopable.', 'video', 'https://assets.mixkit.co/videos/51713/51713-720.mp4', '/posters/mixkit-51713.jpg', null, null, $json${"work":"A steamy river crosses a fantasy forest at night","author":"Mixkit","license":"Mixkit Stock Video Free License","licenseUrl":"https://mixkit.co/license/#videoFree","sourceUrl":"https://mixkit.co/free-stock-video/a-steamy-river-crosses-a-fantasy-forest-at-night-51713/"}$json$::jsonb, 'runway', 'Gen-4', array['fantasy','forest','night','loop']::text[], 800, $json${"mode":"single"}$json$::jsonb, false, 7600, 80, 640, 2176, 80, $json${"counts":{"prompts":1,"settings":1,"assets":0,"editStack":0,"failures":0},"teaser":{"label":"Main","text":"Fantasy forest at night, a steaming river glows softly as it winds betwe"},"failures":[],"settingKeys":["Loop"],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-09-23T22:00:00Z'
from public.profiles p where p.username = 'solenne'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Fantasy forest at night, a steaming river glows softly as it winds between ancient trees, fireflies, moonlight through mist, slow forward glide, seamless loop"}]$json$::jsonb, $json$[{"key":"Loop","value":"On"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb from public.listings where slug = 'enchanted-steam-creek'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'neon-frontier-flyover', p.id, 'Neon frontier flyover', 'Glide over a futuristic landscape of glowing structures. Synthwave in motion.', 'video', 'https://assets.mixkit.co/videos/99544/99544-720.mp4', '/posters/mixkit-99544.jpg', null, null, $json${"work":"Futuristic landscape animation","author":"Mixkit","license":"Mixkit Stock Video Free License","licenseUrl":"https://mixkit.co/license/#videoFree","sourceUrl":"https://mixkit.co/free-stock-video/futuristic-landscape-animation-99544/"}$json$::jsonb, 'kling', '2.5', array['sci-fi','neon','synthwave']::text[], 900, $json${"mode":"single"}$json$::jsonb, false, 6900, 70, 520, 1768, 78, $json${"counts":{"prompts":1,"settings":0,"assets":0,"editStack":0,"failures":0},"teaser":{"label":"Main","text":"Futuristic animated landscape, glowing neon structures on a dark plain, "},"failures":[],"settingKeys":[],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-09-22T17:00:00Z'
from public.profiles p where p.username = 'dax.builds'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Futuristic animated landscape, glowing neon structures on a dark plain, synthwave palette, smooth aerial flyover at dusk"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb from public.listings where slug = 'neon-frontier-flyover'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'speed-line-cyclist', p.id, 'Speed-line cyclist loop', 'A stylised cyclist tears through the frame with comic-book speed lines.', 'video', 'https://assets.mixkit.co/videos/99584/99584-720.mp4', '/posters/mixkit-99584.jpg', null, null, $json${"work":"Animation of a cyclist moving fast","author":"Mixkit","license":"Mixkit Stock Video Free License","licenseUrl":"https://mixkit.co/license/#videoFree","sourceUrl":"https://mixkit.co/free-stock-video/animation-of-a-cyclist-moving-fast-99584/"}$json$::jsonb, 'sora', '2', array['2d','motion','loop','sport']::text[], 600, $json${"mode":"single"}$json$::jsonb, false, 5400, 60, 410, 1394, 77, $json${"counts":{"prompts":1,"settings":0,"assets":0,"editStack":0,"failures":0},"teaser":{"label":"Main","text":"Stylised 2D animation, a cyclist racing at full speed, comic-book speed "},"failures":[],"settingKeys":[],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-09-21T07:00:00Z'
from public.profiles p where p.username = 'kenji_lab'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Stylised 2D animation, a cyclist racing at full speed, comic-book speed lines and motion smears, bold flat colours, seamless loop"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb from public.listings where slug = 'speed-line-cyclist'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'neon-alley-chase', p.id, 'Neon alley chase at golden hour', 'A handheld chase through a wet neon alley. Consistent subject across four cuts with no identity drift.', 'video', 'https://test-videos.co.uk/vids/sintel/mp4/h264/720/Sintel_720_10s_2MB.mp4', 'https://picsum.photos/seed/poster-sintel/900/1600', null, null, null, 'veo', '3.1', array['cinematic','chase','neon']::text[], 1200, $json${"mode":"single"}$json$::jsonb, false, 18420, 214, 1302, 4427, 98, $json${"counts":{"prompts":3,"settings":5,"assets":2,"editStack":3,"failures":3},"teaser":{"label":"Shot 1 · establishing","text":"Handheld 35mm, low angle, a runner in a yellow rain jacket bursts out of"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-neon-1/480/480","note":"Jacket turned red between shots: no subject reference attached."},{"imageUrl":"https://picsum.photos/seed/fail-neon-2/480/480","note":null},{"imageUrl":"https://picsum.photos/seed/fail-neon-3/480/480","note":null}],"settingKeys":["Aspect","Duration","Seed","Guidance","Camera control"],"assetNames":["Runner reference sheet","Neon colour board"],"editTools":["DaVinci Resolve","Topaz Video AI","Resolve Color"]}$json$::jsonb, '2026-09-28T10:00:00Z'
from public.profiles p where p.username = 'mira.frames'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Shot 1 · establishing","text":"Handheld 35mm, low angle, a runner in a yellow rain jacket bursts out of a narrow alley, wet asphalt reflecting pink and teal neon, golden hour haze spilling from the street behind, shallow depth of field, slight motion blur"},{"label":"Shot 2 · tracking","text":"Tracking shot at waist height following the same runner, steam vents, puddle splashes in slow motion at 48fps, keep jacket colour and face identical to reference"},{"label":"Shot 3 · reveal","text":"Whip pan to the end of the alley revealing a crowded night market, warm practical lights, the runner slows and looks back over shoulder"}]$json$::jsonb, $json$[{"key":"Aspect","value":"9:16"},{"key":"Duration","value":"8s per shot"},{"key":"Seed","value":"449120"},{"key":"Guidance","value":"7.5"},{"key":"Camera control","value":"Handheld · medium shake"}]$json$::jsonb, $json$[{"name":"Runner reference sheet","note":"3 angles, used as subject ref"},{"name":"Neon colour board","note":"Pink #ff3e9a / teal mix"}]$json$::jsonb, $json$[{"tool":"DaVinci Resolve","note":"Cut 4 shots, speed ramp into shot 3"},{"tool":"Topaz Video AI","note":"Upscale to 4K, Proteus model"},{"tool":"Resolve Color","note":"Film emulation LUT at 40%"}]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-neon-1/480/480","note":"Jacket turned red between shots: no subject reference attached."},{"imageUrl":"https://picsum.photos/seed/fail-neon-2/480/480","note":"Too much shake. 'Handheld heavy' reads as a found-footage look."},{"imageUrl":"https://picsum.photos/seed/fail-neon-3/480/480","note":"Neon bled into skin tones; fixed with 'practical lights only'."}]$json$::jsonb from public.listings where slug = 'neon-alley-chase'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'liquid-chrome-sneaker', p.id, 'Liquid chrome sneaker reveal', 'Product hero loop: a sneaker forms out of liquid chrome on a seamless backdrop.', 'video', 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', 'https://picsum.photos/seed/poster-flower/900/1600', null, null, null, 'sora', '2', array['product','chrome','loop']::text[], 1800, $json${"mode":"single"}$json$::jsonb, false, 12010, 160, 980, 3332, 91, $json${"counts":{"prompts":1,"settings":4,"assets":1,"editStack":1,"failures":2},"teaser":{"label":"Main","text":"Studio macro, a pool of liquid chrome rises and folds into a high-top sn"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-chrome-1/480/480","note":"Chrome read as grey plastic without the caustics keyword."},{"imageUrl":"https://picsum.photos/seed/fail-chrome-2/480/480","note":null}],"settingKeys":["Aspect","Duration","Loop","Seed"],"assetNames":["Sneaker silhouette mask"],"editTools":["After Effects"]}$json$::jsonb, '2026-09-21T10:00:00Z'
from public.profiles p where p.username = 'mira.frames'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Studio macro, a pool of liquid chrome rises and folds into a high-top sneaker, seamless off-white backdrop, softbox key from top left, caustic reflections, perfectly looping"}]$json$::jsonb, $json$[{"key":"Aspect","value":"9:16"},{"key":"Duration","value":"10s"},{"key":"Loop","value":"On"},{"key":"Seed","value":"88213"}]$json$::jsonb, $json$[{"name":"Sneaker silhouette mask"}]$json$::jsonb, $json$[{"tool":"After Effects","note":"Seamless loop crossfade, 12 frames"}]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-chrome-1/480/480","note":"Chrome read as grey plastic without the caustics keyword."},{"imageUrl":"https://picsum.photos/seed/fail-chrome-2/480/480","note":"Shoe had six eyelets on one side, four on the other."}]$json$::jsonb from public.listings where slug = 'liquid-chrome-sneaker'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'paper-city-timelapse', p.id, 'Paper city day-to-night timelapse', 'A papercraft city folds itself up as the sun sets. Stop-motion feel without the jitter.', 'video', 'https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/720/Big_Buck_Bunny_720_10s_2MB.mp4', 'https://picsum.photos/seed/poster-bunny/900/1600', null, null, null, 'kling', '2.5', array['papercraft','timelapse','stylised']::text[], 900, $json${"mode":"single"}$json$::jsonb, false, 9030, 88, 760, 2584, 87, $json${"counts":{"prompts":2,"settings":3,"assets":0,"editStack":1,"failures":1},"teaser":{"label":"Main","text":"Papercraft city diorama, sun arcs across the sky, buildings fold flat on"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-paper-1/480/480","note":"Paper melted instead of folding at creativity 0.7."}],"settingKeys":["Mode","Duration","Creativity"],"assetNames":[],"editTools":["Premiere Pro"]}$json$::jsonb, '2026-09-30T10:00:00Z'
from public.profiles p where p.username = 'kenji_lab'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Papercraft city diorama, sun arcs across the sky, buildings fold flat one by one as night falls, tiny LED windows switch on, 12fps stop-motion cadence, top-down three-quarter view"},{"label":"Negative","text":"jitter, warping, melting paper, text"}]$json$::jsonb, $json$[{"key":"Mode","value":"Professional"},{"key":"Duration","value":"10s"},{"key":"Creativity","value":"0.4"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"tool":"Premiere Pro","note":"Frame-hold every other frame for 12fps"}]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-paper-1/480/480","note":"Paper melted instead of folding at creativity 0.7."}]$json$::jsonb from public.listings where slug = 'paper-city-timelapse'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'koi-pond-loop', p.id, 'Koi pond ink-wash loop', 'Sumi-e style koi circling in a seamless loop. Great for ambient screens.', 'video', 'https://test-videos.co.uk/vids/jellyfish/mp4/h264/720/Jellyfish_720_10s_2MB.mp4', 'https://picsum.photos/seed/poster-jellyfish/900/1600', null, null, null, 'runway', 'Gen-4', array['ink','loop','ambient']::text[], 0, $json${"mode":"single"}$json$::jsonb, false, 22100, 1430, 2200, 7480, 84, $json${"counts":{"prompts":1,"settings":2,"assets":0,"editStack":1,"failures":1},"teaser":{"label":"Main","text":"Traditional sumi-e ink wash painting of three koi circling slowly in a p"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-koi-1/480/480","note":"Koi multiplied to seven without 'three koi' in the first clause."}],"settingKeys":["Duration","Motion"],"assetNames":[],"editTools":["After Effects"]}$json$::jsonb, '2026-09-12T10:00:00Z'
from public.profiles p where p.username = 'kenji_lab'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Traditional sumi-e ink wash painting of three koi circling slowly in a pond, rice paper texture, ink bleeding softly at the edges, seamless loop, overhead view"}]$json$::jsonb, $json$[{"key":"Duration","value":"10s"},{"key":"Motion","value":"3"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"tool":"After Effects","note":"Paper grain overlay at 15%"}]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-koi-1/480/480","note":"Koi multiplied to seven without 'three koi' in the first clause."}]$json$::jsonb from public.listings where slug = 'koi-pond-loop'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'desert-drone-sweep', p.id, 'Desert drone sweep over a lost city', 'A long FPV-style sweep over sandstone ruins with consistent geography.', 'video', 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/friday.mp4', 'https://picsum.photos/seed/poster-friday/900/1600', null, null, null, 'veo', '3.1', array['drone','landscape','epic']::text[], 1500, $json${"mode":"single"}$json$::jsonb, false, 7400, 61, 512, 1741, 79, $json${"counts":{"prompts":1,"settings":2,"assets":1,"editStack":1,"failures":1},"teaser":{"label":"Main","text":"FPV drone sweep low over sandstone ruins of an ancient city at dawn, lon"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-desert-1/480/480","note":"Archway duplicated mid-shot without the layout reference."}],"settingKeys":["Aspect","Seed"],"assetNames":["Valley layout sketch"],"editTools":["DaVinci Resolve"]}$json$::jsonb, '2026-09-25T10:00:00Z'
from public.profiles p where p.username = 'dax.builds'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"FPV drone sweep low over sandstone ruins of an ancient city at dawn, long shadows, dust in the air, accelerating through an archway then rising to reveal the full valley"}]$json$::jsonb, $json$[{"key":"Aspect","value":"9:16"},{"key":"Seed","value":"70031"}]$json$::jsonb, $json$[{"name":"Valley layout sketch"}]$json$::jsonb, $json$[{"tool":"DaVinci Resolve","note":"Speed ramp 100→140%"}]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-desert-1/480/480","note":"Archway duplicated mid-shot without the layout reference."}]$json$::jsonb from public.listings where slug = 'desert-drone-sweep'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'velvet-portrait-series', p.id, 'Velvet portrait series', 'Editorial portraits with deep velvet backdrops and painterly skin.', 'image', 'https://picsum.photos/seed/velvet-portrait/900/1600', 'https://picsum.photos/seed/velvet-portrait/900/1600', array['https://picsum.photos/seed/velvet-portrait/900/1600','https://picsum.photos/seed/velvet-portrait-2/1200/1200','https://picsum.photos/seed/velvet-portrait-3/1080/1350']::text[], null, null, 'midjourney', 'v7', array['portrait','editorial','painterly']::text[], 800, $json${"mode":"single"}$json$::jsonb, false, 15300, 302, 1890, 6426, 95, $json${"counts":{"prompts":1,"settings":3,"assets":1,"editStack":2,"failures":2},"teaser":{"label":"Main","text":"Editorial portrait of a woman in a deep emerald velvet blazer against cr"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-velvet-1/480/480","note":"Stylize 750 made faces waxy."},{"imageUrl":"https://picsum.photos/seed/fail-velvet-2/480/480","note":null}],"settingKeys":["Aspect","Stylize","Style ref"],"assetNames":["Moodboard (6 images)"],"editTools":["Photoshop","Lightroom"]}$json$::jsonb, '2026-09-29T10:00:00Z'
from public.profiles p where p.username = 'solenne'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Editorial portrait of a woman in a deep emerald velvet blazer against crushed burgundy velvet, Rembrandt lighting, painterly skin texture, medium format film, 85mm"}]$json$::jsonb, $json$[{"key":"Aspect","value":"--ar 9:16"},{"key":"Stylize","value":"250"},{"key":"Style ref","value":"--sref 2219400"}]$json$::jsonb, $json$[{"name":"Moodboard (6 images)"}]$json$::jsonb, $json$[{"tool":"Photoshop","note":"Frequency separation, light dodge & burn"},{"tool":"Lightroom","note":"Grain 20, split tone"}]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-velvet-1/480/480","note":"Stylize 750 made faces waxy."},{"imageUrl":"https://picsum.photos/seed/fail-velvet-2/480/480","note":"'Velvet' alone read as satin; 'crushed velvet' fixed it."}]$json$::jsonb from public.listings where slug = 'velvet-portrait-series'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'brutalist-greenhouse', p.id, 'Brutalist greenhouse interior', 'Concrete and fern interiors with soft overcast light.', 'image', 'https://picsum.photos/seed/brutalist-greenhouse/1200/1200', 'https://picsum.photos/seed/brutalist-greenhouse/1200/1200', array['https://picsum.photos/seed/brutalist-greenhouse/1200/1200']::text[], null, null, 'flux', '1.1 Pro', array['architecture','interior','plants']::text[], 600, $json${"mode":"single"}$json$::jsonb, false, 6100, 74, 640, 2176, 72, $json${"counts":{"prompts":1,"settings":3,"assets":0,"editStack":1,"failures":1},"teaser":{"label":"Main","text":"Interior of a brutalist concrete greenhouse, tall board-formed walls, ha"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-green-1/480/480","note":"Guidance 6 over-sharpened the concrete into CGI."}],"settingKeys":["Steps","Guidance","Seed"],"assetNames":[],"editTools":["Lightroom"]}$json$::jsonb, '2026-09-18T10:00:00Z'
from public.profiles p where p.username = 'dax.builds'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Interior of a brutalist concrete greenhouse, tall board-formed walls, hanging ferns and monstera, overcast skylight, soft mist, architectural photography, tilt-shift lens"}]$json$::jsonb, $json$[{"key":"Steps","value":"40"},{"key":"Guidance","value":"3.5"},{"key":"Seed","value":"120045"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"tool":"Lightroom","note":"Perspective correction"}]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-green-1/480/480","note":"Guidance 6 over-sharpened the concrete into CGI."}]$json$::jsonb from public.listings where slug = 'brutalist-greenhouse'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'retro-poster-type', p.id, 'Retro travel poster with perfect type', '1960s travel-poster style with legible, correctly kerned headline type.', 'image', 'https://picsum.photos/seed/retro-poster/1600/1000', 'https://picsum.photos/seed/retro-poster/1600/1000', array['https://picsum.photos/seed/retro-poster/1600/1000','https://picsum.photos/seed/retro-poster-2/1080/1350']::text[], null, null, 'ideogram', '3.0', array['poster','typography','retro']::text[], 500, $json${"mode":"single"}$json$::jsonb, false, 4300, 52, 410, 1394, 64, $json${"counts":{"prompts":1,"settings":2,"assets":0,"editStack":0,"failures":1},"teaser":{"label":"Main","text":"Vintage 1960s travel poster for \"LISBOA\", screen-printed look, limited p"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-poster-1/480/480","note":"Magic prompt rewrote the city name."}],"settingKeys":["Magic prompt","Style"],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-09-08T10:00:00Z'
from public.profiles p where p.username = 'solenne'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Vintage 1960s travel poster for \"LISBOA\", screen-printed look, limited palette of five colours, tram climbing a hill, bold condensed sans-serif headline"}]$json$::jsonb, $json$[{"key":"Magic prompt","value":"Off"},{"key":"Style","value":"Design"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-poster-1/480/480","note":"Magic prompt rewrote the city name."}]$json$::jsonb from public.listings where slug = 'retro-poster-type'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'macro-dew-insects', p.id, 'Macro dew on iridescent beetles', 'Ultra-macro nature shots with believable depth of field.', 'image', 'https://picsum.photos/seed/macro-beetle/900/1600', 'https://picsum.photos/seed/macro-beetle/900/1600', null, null, null, 'imagen', '4', array['macro','nature']::text[], 0, $json${"mode":"single"}$json$::jsonb, false, 8800, 900, 700, 2380, 70, $json${"counts":{"prompts":1,"settings":1,"assets":0,"editStack":0,"failures":1},"teaser":{"label":"Main","text":"Ultra macro photograph of an iridescent jewel beetle covered in morning "},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-macro-1/480/480","note":"Beetle had eight legs. Name the species to anchor anatomy."}],"settingKeys":["Aspect"],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-09-02T10:00:00Z'
from public.profiles p where p.username = 'mira.frames'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Ultra macro photograph of an iridescent jewel beetle covered in morning dew on a fern frond, focus stacked, soft green bokeh, 100mm macro lens"}]$json$::jsonb, $json$[{"key":"Aspect","value":"9:16"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-macro-1/480/480","note":"Beetle had eight legs. Name the species to anchor anatomy."}]$json$::jsonb from public.listings where slug = 'macro-dew-insects'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'floating-islands-matte', p.id, 'Floating islands matte painting', 'Classic matte painting look for fantasy establishing shots.', 'image', 'https://picsum.photos/seed/floating-islands/1600/900', 'https://picsum.photos/seed/floating-islands/1600/900', array['https://picsum.photos/seed/floating-islands/1600/900','https://picsum.photos/seed/floating-islands-2/900/1600','https://picsum.photos/seed/floating-islands-3/1200/1200','https://picsum.photos/seed/floating-islands-4/1600/1000']::text[], null, null, 'midjourney', 'v7', array['fantasy','matte painting']::text[], 1000, $json${"mode":"single"}$json$::jsonb, false, 10200, 120, 990, 3366, 88, $json${"counts":{"prompts":1,"settings":2,"assets":0,"editStack":1,"failures":1},"teaser":{"label":"Main","text":"Matte painting of floating islands with waterfalls pouring into clouds, "},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-islands-1/480/480","note":"Chaos 40 gave a different world each time."}],"settingKeys":["Aspect","Chaos"],"assetNames":[],"editTools":["Photoshop"]}$json$::jsonb, '2026-09-26T10:00:00Z'
from public.profiles p where p.username = 'kenji_lab'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Matte painting of floating islands with waterfalls pouring into clouds, tiny monastery on the largest island, golden rim light, painted by a 1980s film matte artist"}]$json$::jsonb, $json$[{"key":"Aspect","value":"--ar 9:16"},{"key":"Chaos","value":"10"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"tool":"Photoshop","note":"Generative expand for the top sky"}]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-islands-1/480/480","note":"Chaos 40 gave a different world each time."}]$json$::jsonb from public.listings where slug = 'floating-islands-matte'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'ceramic-still-life', p.id, 'Soft ceramic still life', 'Minimal still lifes of matte ceramics and dried flowers.', 'image', 'https://picsum.photos/seed/ceramic-still/900/1600', 'https://picsum.photos/seed/ceramic-still/900/1600', null, null, null, 'flux', '1.1 Pro', array['still life','minimal']::text[], 400, $json${"mode":"single"}$json$::jsonb, false, 3900, 33, 280, 952, 58, $json${"counts":{"prompts":1,"settings":1,"assets":0,"editStack":0,"failures":0},"teaser":{"label":"Main","text":"Minimal still life, matte off-white ceramic vases of varying heights, a "},"failures":[],"settingKeys":["Steps"],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-09-15T10:00:00Z'
from public.profiles p where p.username = 'solenne'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Minimal still life, matte off-white ceramic vases of varying heights, a single stem of dried pampas grass, warm side light, linen backdrop"}]$json$::jsonb, $json$[{"key":"Steps","value":"32"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb from public.listings where slug = 'ceramic-still-life'
on conflict (listing_id) do nothing;

insert into public.listings (slug, creator_id, title, description, type, media_url, poster_url, images, clip, credit, tool, tool_version, tags, price_cents, pricing, is_adult, views, sales, saves, likes, trending_score, preview, created_at)
select 'rooftop-rain-portrait', p.id, 'Rooftop rain portrait', 'Night portrait in the rain with city bokeh. Sharp eyes, believable water.', 'image', 'https://picsum.photos/seed/rooftop-rain/900/1600', 'https://picsum.photos/seed/rooftop-rain/900/1600', null, null, null, 'runway', 'Frames', array['portrait','rain','night']::text[], 700, $json${"mode":"single"}$json$::jsonb, false, 5200, 45, 390, 1326, 76, $json${"counts":{"prompts":1,"settings":1,"assets":0,"editStack":0,"failures":1},"teaser":{"label":"Main","text":"Night portrait of a man on a rooftop in heavy rain, city bokeh behind, w"},"failures":[{"imageUrl":"https://picsum.photos/seed/fail-rain-1/480/480","note":"Rain froze into streaks. Add 'shutter 1/1000'."}],"settingKeys":["Style"],"assetNames":[],"editTools":[]}$json$::jsonb, '2026-09-27T10:00:00Z'
from public.profiles p where p.username = 'dax.builds'
on conflict (slug) do nothing;
insert into public.recipes (listing_id, prompts, settings, assets, edit_stack, failures)
select id, $json$[{"label":"Main","text":"Night portrait of a man on a rooftop in heavy rain, city bokeh behind, water droplets on skin, umbrella-less, cinematic teal and amber, 50mm f/1.4"}]$json$::jsonb, $json$[{"key":"Style","value":"Cinematic"}]$json$::jsonb, $json$[]$json$::jsonb, $json$[]$json$::jsonb, $json$[{"imageUrl":"https://picsum.photos/seed/fail-rain-1/480/480","note":"Rain froze into streaks. Add 'shutter 1/1000'."}]$json$::jsonb from public.listings where slug = 'rooftop-rain-portrait'
on conflict (listing_id) do nothing;

